services:
  activemq:
    image: apache/activemq:6.3.0
    container_name: learning-activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_CONNECTION_USER: student
      ACTIVEMQ_CONNECTION_PASSWORD: student
      ACTIVEMQ_WEB_USER: student
      ACTIVEMQ_WEB_PASSWORD: student

  discovery-server:
    build: ./backend/discovery-server
    ports:
      - "8761:8761"
    depends_on:
      - activemq

  order-service:
    build: ./backend/order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - activemq
      - discovery-server

  email-service:
    build: ./backend/email-service
    ports:
      - "8082:8082"
    environment:
      SPRING_ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    depends_on:
      - activemq
      - discovery-server

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - order-service
