import { useEffect, useState } from "react";
const API_URL="http://localhost:8081/orders", EMAIL_URL="http://localhost:8082/emails", EMPTY={customerEmail:"",product:"",quantity:1};
export default function App(){const [form,setForm]=useState(EMPTY),[orders,setOrders]=useState([]),[emails,setEmails]=useState([]),[error,setError]=useState("");
 const load=async()=>{try{const r=await fetch(API_URL);setOrders(await r.json())}catch(e){setError(e.message)}};
 const loadEmails=async()=>{try{const r=await fetch(EMAIL_URL);if(r.ok)setEmails(await r.json())}catch(e){}};
 useEffect(()=>{load();loadEmails();const t=setInterval(loadEmails,1000);return()=>clearInterval(t)},[]);
 function change(e){const{name,value}=e.target;setForm({...form,[name]:name==="quantity"?Number(value):value})}
 async function submit(e){e.preventDefault();try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!r.ok)throw Error(`Could not create order (${r.status})`);setForm(EMPTY);load();loadEmails()}catch(x){setError(x.message)}}
 return <main><h1>Order lab</h1><p>Create an order and watch ActiveMQ deliver the event.</p><form onSubmit={submit}><label>Customer email<input name="customerEmail" type="email" value={form.customerEmail} onChange={change} required/></label><label>Product<input name="product" value={form.product} onChange={change} required/></label><label>Quantity<input name="quantity" type="number" min="1" value={form.quantity} onChange={change} required/></label><button>Create order</button></form>{error&&<p className="error">{error}</p>}<section><h2>Orders</h2><ul>{orders.map(o=><li key={o.id}><strong>{o.product}</strong> × {o.quantity}<span>{o.customerEmail}</span></li>)}</ul></section><section><h2>Emails consumed by ActiveMQ</h2>{emails.length?<ul>{[...emails].reverse().map(e=><li key={e.orderId}><strong>Email sent</strong> — {e.product} × {e.quantity}<span>{e.customerEmail}</span></li>)}</ul>:<p>No messages consumed yet.</p>}</section></main>}
